// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPtx0RaLfeRjhpm8iFjQqx5rhMUWkOh-w',
    appId: '1:707350493338:web:c4c786172feef2bc470723',
    messagingSenderId: '707350493338',
    projectId: 'task-hub-1e169',
    authDomain: 'task-hub-1e169.firebaseapp.com',
    storageBucket: 'task-hub-1e169.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3Hz_nW14kaemywYCrWWuAXZQSWi46D0',
    appId: '1:707350493338:android:82f426bf4a0cae38470723',
    messagingSenderId: '707350493338',
    projectId: 'task-hub-1e169',
    storageBucket: 'task-hub-1e169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_rqte3jDTXVFKlTS-0bNAxux5pKnsArM',
    appId: '1:707350493338:ios:0991ed3a5af7ec32470723',
    messagingSenderId: '707350493338',
    projectId: 'task-hub-1e169',
    storageBucket: 'task-hub-1e169.appspot.com',
    iosBundleId: 'com.example.taskHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_rqte3jDTXVFKlTS-0bNAxux5pKnsArM',
    appId: '1:707350493338:ios:a36e2f54f76cde35470723',
    messagingSenderId: '707350493338',
    projectId: 'task-hub-1e169',
    storageBucket: 'task-hub-1e169.appspot.com',
    iosBundleId: 'com.example.taskHub.RunnerTests',
  );
}
